/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Hospital_UserInterface;

import HospitalMngmt.City;
import HospitalMngmt.Community;
import HospitalMngmt.SystemAdmin;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adityaillur
 */
public class AdminAddCommunityPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientSearchNearbyHospital
     */
    public AdminAddCommunityPanel() {
        initComponents();
        fillTable();
        fillTable1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddCommunity = new javax.swing.JButton();
        txtCommunityName = new javax.swing.JTextField();
        lblCommunityName = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCity = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCommunity = new javax.swing.JTable();
        lblPassword = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddCommunity.setFont(new java.awt.Font("Silom", 1, 18)); // NOI18N
        btnAddCommunity.setText("Add Community");
        btnAddCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCommunityActionPerformed(evt);
            }
        });
        add(btnAddCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 426, -1, -1));
        add(txtCommunityName, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 431, 205, -1));

        lblCommunityName.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblCommunityName.setText("Community Name");
        add(lblCommunityName, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 428, -1, -1));

        lblTitle.setFont(new java.awt.Font("Silom", 1, 36)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Add Community");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 845, 64));

        tblCity.setBackground(new java.awt.Color(51, 153, 255));
        tblCity.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "City"
            }
        ));
        jScrollPane1.setViewportView(tblCity);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 76, 766, 176));

        tblCommunity.setBackground(new java.awt.Color(51, 153, 255));
        tblCommunity.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Community Name", "Community"
            }
        ));
        jScrollPane2.setViewportView(tblCommunity);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 474, 766, 176));

        lblPassword.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblPassword.setText("Password");
        add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 314, -1, -1));

        lblUsername.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblUsername.setText("Username");
        add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 270, -1, -1));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 317, 248, -1));
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 273, 248, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCommunityActionPerformed
        // TODO add your handling code here:
        if(tblCity.getSelectedRow()>-1) {
         City c = (City)tblCity.getValueAt(tblCity.getSelectedRow(),1);
         Community b = new Community(txtCommunityName.getText(),c);
         SystemAdmin.communityList.add(b);
         fillTable1();
        }
        else{
             JOptionPane.showMessageDialog(null, "Please Select City");
        }
    }//GEN-LAST:event_btnAddCommunityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCommunity;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCommunityName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTable tblCity;
    private javax.swing.JTable tblCommunity;
    private javax.swing.JTextField txtCommunityName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
private void fillTable() {
       DefaultTableModel model = (DefaultTableModel)tblCity.getModel();
       model.setRowCount(0);
       for(City  p : SystemAdmin.cityList ){
           
           Object[] row = new Object[2];
           row[0]= p.getName();
           row[1]= p;
           
           
           
           model.addRow(row);
       }}

private void fillTable1() {
       DefaultTableModel model = (DefaultTableModel)tblCommunity.getModel();
       model.setRowCount(0);
       for(Community  p : SystemAdmin.communityList ){
           
           Object[] row = new Object[2];
           row[0]= p.getName();
           row[1]= p;
 
           model.addRow(row);
       }}

} 


