/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Hospital_UserInterface;

import HospitalMngmt.Encounter;
import HospitalMngmt.Doctor;
import HospitalMngmt.SystemAdmin;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author adityaillur
 */
public class DoctorViewAppointmentPanel extends javax.swing.JPanel {
    public Doctor doctor;
    private TableRowSorter<TableModel> sorter; 
    /**
     * Creates new form DoctorViewAppointment
     */
    public DoctorViewAppointmentPanel(Doctor p) {
        initComponents();
        doctor=p;
        fillTable();
        sorter = new TableRowSorter<>(tblViewHospital.getModel());
        tblViewHospital.setRowSorter(sorter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblCommunity = new javax.swing.JLabel();
        lblPatientID = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPatientID = new javax.swing.JTextField();
        lblVitalSigns = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        txtCommunity = new javax.swing.JTextField();
        lblSpecialisation = new javax.swing.JLabel();
        txtVitalSigns = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewHospital = new javax.swing.JTable();
        lblGender = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        txtSearch = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();

        lblName.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblName.setText("Name");

        lblCommunity.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblCommunity.setText("Community");

        lblPatientID.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblPatientID.setText("Patient ID");

        txtPatientID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientIDActionPerformed(evt);
            }
        });
        txtPatientID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPatientIDKeyReleased(evt);
            }
        });

        lblVitalSigns.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblVitalSigns.setText("Vital Signs");

        btnUpdate.setFont(new java.awt.Font("Silom", 1, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblSpecialisation.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblSpecialisation.setText("City");

        txtVitalSigns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVitalSignsActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Silom", 1, 36)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("View Appointments");

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        tblViewHospital.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Gender", "City", "Community", "Vital Signs", "Encounter Obj"
            }
        ));
        tblViewHospital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewHospitalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblViewHospital);

        lblGender.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblGender.setText("Gender");

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        lblSearch.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblSearch.setText("Search");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCommunity)
                    .addComponent(lblVitalSigns)
                    .addComponent(lblSpecialisation)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCommunity)
                                .addComponent(txtCity)
                                .addComponent(txtVitalSigns, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnUpdate)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblPatientID)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblName)
                                .addComponent(lblGender))
                            .addGap(122, 122, 122)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(2, 2, 2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSearch)
                        .addGap(122, 122, 122)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearch))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatientID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGender))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblSpecialisation)
                        .addGap(20, 20, 20)
                        .addComponent(lblCommunity)
                        .addGap(18, 18, 18)
                        .addComponent(lblVitalSigns))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtVitalSigns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addComponent(btnUpdate)
                .addGap(61, 61, 61))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPatientIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientIDActionPerformed

    private void txtPatientIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPatientIDKeyReleased
        // TODO add your handling code here:
//        String regexString = "";
//        Pattern pattern = Pattern.compile(regexString);
//        Matcher matcher = pattern.matcher("Visit W3Schools!");
//        boolean matchFound = matcher.find();
//        if(matchFound) {
//
//        } else {
//
//            System.out.println("Match not found");
//        }

        
    }//GEN-LAST:event_txtPatientIDKeyReleased

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String textBoxString = txtSearch.getText();
        sorter.setRowFilter(RowFilter.regexFilter(textBoxString));
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String vitals = txtVitalSigns.getText();
        DefaultTableModel model = (DefaultTableModel)tblViewHospital.getModel();
        Encounter p = (Encounter)model.getValueAt(tblViewHospital.getSelectedRow(), 6);
        p.vitalSigns=vitals;
        fillTable();
        SystemAdmin.doctorList.add(doctor);
        JOptionPane.showMessageDialog(null, "Vitals Added");
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblViewHospitalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewHospitalMouseClicked
        // TODO add your handling code here:
        if(tblViewHospital.getSelectedRow()>-1 ){
            DefaultTableModel model = (DefaultTableModel)tblViewHospital.getModel();
        
            Encounter p = (Encounter)model.getValueAt(tblViewHospital.getSelectedRow(), 6);
            txtPatientID.setText(String.valueOf(p.patient.patientID));

            txtName.setText(p.patient.name);
            txtGender.setText(p.patient.gender);

            txtCity.setText(p.patient.city);
            txtCommunity.setText(p.patient.community);
        }
    }//GEN-LAST:event_tblViewHospitalMouseClicked

    private void txtVitalSignsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVitalSignsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVitalSignsActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPatientID;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSpecialisation;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVitalSigns;
    private javax.swing.JTable tblViewHospital;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCommunity;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtVitalSigns;
    // End of variables declaration//GEN-END:variables

private void fillTable() {
       DefaultTableModel model = (DefaultTableModel)tblViewHospital.getModel();
       model.setRowCount(0);
       for(Encounter  p : SystemAdmin.encounterList ){
           if(p.doctor==this.doctor){
           Object[] row = new Object[7];
           row[0]= p.patient.patientID;
           row[1]= p.patient.name;
           
           row[2]= p.patient.gender;
           row[3]= p.patient.city;
           
           
           row[4]= p.patient.community;
//           row[5]=p.vitalSigns;           
           row[6]= p;
           
           
           model.addRow(row);
       }}}

}
