/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Hospital_UserInterface;

/**
 *
 * @author adityaillur
 */
public class MainLogin extends javax.swing.JFrame {

    /**
     * Creates new form MainLogin
     */
    public MainLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        btnSysAdmin = new javax.swing.JButton();
        btnComAdmin = new javax.swing.JButton();
        btnDoc = new javax.swing.JButton();
        btnPatient = new javax.swing.JButton();
        btnHosAdmin = new javax.swing.JButton();
        lblBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogin.setBackground(new java.awt.Color(51, 204, 255));
        lblLogin.setFont(new java.awt.Font("Phosphate", 1, 48)); // NOI18N
        lblLogin.setText("LOGIN AS");
        lblLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 210, 70));

        btnSysAdmin.setBackground(new java.awt.Color(204, 204, 204));
        btnSysAdmin.setFont(new java.awt.Font("Telugu MN", 1, 18)); // NOI18N
        btnSysAdmin.setText("System Admin");
        btnSysAdmin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSysAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSysAdminActionPerformed(evt);
            }
        });
        jPanel1.add(btnSysAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 140, 60));

        btnComAdmin.setBackground(new java.awt.Color(204, 204, 204));
        btnComAdmin.setFont(new java.awt.Font("Telugu MN", 1, 18)); // NOI18N
        btnComAdmin.setText("Community Admin");
        btnComAdmin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnComAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComAdminActionPerformed(evt);
            }
        });
        jPanel1.add(btnComAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, 60));

        btnDoc.setBackground(new java.awt.Color(204, 204, 204));
        btnDoc.setFont(new java.awt.Font("Telugu MN", 1, 18)); // NOI18N
        btnDoc.setText("Doctor");
        btnDoc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocActionPerformed(evt);
            }
        });
        jPanel1.add(btnDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 110, 60));

        btnPatient.setBackground(new java.awt.Color(204, 204, 204));
        btnPatient.setFont(new java.awt.Font("Telugu MN", 1, 18)); // NOI18N
        btnPatient.setText("Patient");
        btnPatient.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientActionPerformed(evt);
            }
        });
        jPanel1.add(btnPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 110, 60));

        btnHosAdmin.setBackground(new java.awt.Color(204, 204, 204));
        btnHosAdmin.setFont(new java.awt.Font("October Devanagari", 1, 18)); // NOI18N
        btnHosAdmin.setText("Hospital Admin");
        btnHosAdmin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHosAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHosAdminActionPerformed(evt);
            }
        });
        jPanel1.add(btnHosAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 170, 60));

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hospital_UserInterface/Hospital Mnagement.jpg"))); // NOI18N
        lblBack.setText("jLabel1");
        jPanel1.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSysAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSysAdminActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new SysAdminLogin().setVisible(true);   
    }//GEN-LAST:event_btnSysAdminActionPerformed

    private void btnComAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComAdminActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new CommunityLogin().setVisible(true);  
    }//GEN-LAST:event_btnComAdminActionPerformed

    private void btnDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new DoctorLogin().setVisible(true);  
    }//GEN-LAST:event_btnDocActionPerformed

    private void btnPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new PatientLogin().setVisible(true);  
    }//GEN-LAST:event_btnPatientActionPerformed

    private void btnHosAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHosAdminActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new HospitalLogin().setVisible(true);  
    }//GEN-LAST:event_btnHosAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComAdmin;
    private javax.swing.JButton btnDoc;
    private javax.swing.JButton btnHosAdmin;
    private javax.swing.JButton btnPatient;
    private javax.swing.JButton btnSysAdmin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblLogin;
    // End of variables declaration//GEN-END:variables
}
